# Generated by Django 4.2.6 on 2023-10-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
