# Generated by Django 4.2.6 on 2023-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0002_mainstorage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(blank=True, db_column='user_photo', null=True, upload_to='profile_images'),
        ),
    ]
