# Generated by Django 4.2.6 on 2023-10-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0004_remove_userprofile_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
