# Generated by Django 4.2.6 on 2023-10-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0006_useravatar_delete_phoneimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstorage',
            name='image_url',
        ),
    ]
