# Generated by Django 4.2.6 on 2023-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0009_alter_useravatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
