# Generated by Django 4.2.6 on 2023-11-06 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0011_alter_useravatar_options_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='phone_type',
            field=models.CharField(choices=[('S18', 'S18'), ('A60', 'A60'), ('A04', 'A04'), ('A18', 'A18'), ('C20', 'C20'), ('C19', 'C19'), ('S10', 'S10'), ('10C8G', '10C8G'), ('10C', '10C'), ('8C', '8C'), ('P7P4G', 'P7P4G'), ('P7P3G', 'P7P3G'), ('P7', 'P7'), ('S9', 'S9'), ('9T', '9T'), ('S8', 'S8'), ('S7', 'S7')], default='S18', max_length=25),
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='phone_type',
            field=models.CharField(choices=[('S18', 'S18'), ('A60', 'A60'), ('A04', 'A04'), ('A18', 'A18'), ('C20', 'C20'), ('C19', 'C19'), ('S10', 'S10'), ('10C8G', '10C8G'), ('10C', '10C'), ('8C', '8C'), ('P7P4G', 'P7P4G'), ('P7P3G', 'P7P3G'), ('P7', 'P7'), ('S9', 'S9'), ('9T', '9T'), ('S8', 'S8'), ('S7', 'S7')], default='S18', max_length=25),
        ),
    ]
