# Generated by Django 4.2.6 on 2023-11-06 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0012_alter_customerdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 11, 6)),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='update_at',
            field=models.DateField(default=datetime.date(2023, 11, 6)),
        ),
    ]
