# Generated by Django 4.2.6 on 2023-11-06 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0013_alter_customerdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 6, 11, 9, 31, 240649, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='update_at',
            field=models.DateField(default=datetime.datetime(2023, 11, 6, 11, 9, 31, 240711, tzinfo=datetime.timezone.utc)),
        ),
    ]
