# Generated by Django 4.2.6 on 2023-11-07 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0015_remove_customerdata_working_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='update_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
