# Generated by Django 4.2.6 on 2023-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0016_alter_customerdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstorage',
            name='category',
            field=models.CharField(choices=[('Tecno', 'Tecno'), ('Itel', 'Itel'), ('Infinix', 'Infinix'), ('Redmi', 'Redmi')], default='Tecno', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='spec',
            field=models.CharField(choices=[('8+256', '8+256'), ('4+256', '4+256'), ('8+128', '8+128'), ('4+128', '4+128'), ('4+64', '4+64'), ('3+64', '3+64'), ('2+64', '2+64'), ('3+32', '3+32'), ('2+32', '2+32'), ('1+32', '1+32'), ('2+16', '2+16')], default='8+256', max_length=25, null=True),
        ),
    ]
