# Generated by Django 4.2.6 on 2023-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0017_alter_mainstorage_category_alter_mainstorage_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstorage',
            name='battery',
            field=models.CharField(choices=[('6000mAh', '6000mAh'), ('5000mAh', '5000mAh'), ('4000mAh', '4000mAh'), ('3000mAh', '3000mAh'), ('2500mAh', '2500mAh'), ('2000mAh', '2000mAh'), ('1500mAh', '1500mAh'), ('1000mAh', '1000mAh')], default='6000mAh', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='camera',
            field=models.CharField(choices=[('200MP', '200MP'), ('160MP', '160MP'), ('130MP', '130MP'), ('100MP', '100MP'), ('80MP', '80MP'), ('64MP', '64MP'), ('50MP', '50MP'), ('48MP', '48MP'), ('32MP', '32MP'), ('24MP', '24MP'), ('16MP', '16MP'), ('13MP', '13MP'), ('12MP', '12MP'), ('8MP', '8MP'), ('5MP', '5MP')], default='200MP', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='os',
            field=models.CharField(choices=[('Android 13', 'Android 13'), ('Android 12', 'Android 12'), ('Android 11', 'Android 11'), ('Android 10', 'Android 10'), ('Android 9', 'Android 9'), ('Android 8', 'Android 8'), ('Android 7', 'Android 7')], default='Android 13', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='sales_type',
            field=models.CharField(choices=[('##', '##'), ('Cash', 'Cash'), ('Loan', 'Loan')], default='##', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='screen_size',
            field=models.CharField(choices=[('6.8 inch HD+ display', '6.8 inch HD+ display'), ('6.6 inch HD+ display', '6.6 inch HD+ display'), ('6.5 inch HD+ display', '6.5 inch HD+ display'), ('6.52 inch HD+ display', '6.52 inch HD+ display'), ('6.5 inch HD+ display', '6.5 inch HD+ display'), ('6.52 inch HD+ display', '6.52 inch HD+ display'), ('6.3 inch HD+ display', '6.3 inch HD+ display'), ('5.5 inch HD+ display', '5.5 inch HD+ display')], default='6.8 inch HD+ display', max_length=25, null=True),
        ),
    ]
