# Generated by Django 4.2.6 on 2023-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0018_alter_mainstorage_battery_alter_mainstorage_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='assigned_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainstorage',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
