# Generated by Django 4.2.6 on 2023-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0019_mainstorage_assigned_from_mainstorage_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
