# Generated by Django 4.2.6 on 2023-11-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0020_mainstorage_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstorage',
            name='assigned_to',
        ),
    ]
