# Generated by Django 4.2.6 on 2023-11-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0021_remove_mainstorage_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
