# Generated by Django 4.2.6 on 2023-11-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0023_remove_customerdata_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='witness_id_no',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
