# Generated by Django 4.2.6 on 2023-11-13 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0024_customerdata_rejected_customerdata_witness_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Aitel_mifi_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved', models.BooleanField(default=False)),
                ('device_imei', models.CharField(max_length=15, unique=True)),
                ('device', models.CharField(choices=[('S18', 'S18'), ('A60', 'A60'), ('A04', 'A04'), ('A18', 'A18'), ('C20', 'C20'), ('C19', 'C19'), ('S10', 'S10'), ('10C8G', '10C8G'), ('10C', '10C'), ('8C', '8C'), ('P7P4G', 'P7P4G'), ('P7P3G', 'P7P3G'), ('P7', 'P7'), ('S9', 'S9'), ('9T', '9T'), ('S8', 'S8'), ('S7', 'S7')], default='S18', max_length=25)),
                ('pending', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('inactive', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('assigned', models.BooleanField(default=False)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('stock_out_date', models.DateField(default=django.utils.timezone.now)),
                ('cash_recieved', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device_imei', 'device', 'in_stock', 'assigned'], name='system_core_device__d21b0e_idx')],
            },
        ),
    ]
