# Generated by Django 4.2.6 on 2023-11-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0025_mainstorage_pending_aitel_mifi_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitel_mifi_storage',
            name='device',
            field=models.CharField(choices=[('MIFI', 'MIFI'), ('ROUTER (IUD)', 'ROUTER (IUD)')], default='MIFI', max_length=25),
        ),
        migrations.DeleteModel(
            name='AgentStock',
        ),
    ]
