# Generated by Django 4.2.6 on 2023-11-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0026_alter_aitel_mifi_storage_device_delete_agentstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitel_mifi_storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='phone_type',
            field=models.CharField(choices=[('S18', 'S18'), ('A60', 'A60'), ('A04', 'A04'), ('A18', 'A18'), ('C20', 'C20'), ('C19', 'C19'), ('S10Pro', 'S10Pro'), ('S10', 'S10'), ('10C8G', '10C8G'), ('10C', '10C'), ('8C', '8C'), ('P7P4G', 'P7P4G'), ('P7P3G', 'P7P3G'), ('P7', 'P7'), ('S9', 'S9'), ('9T', '9T'), ('S8', 'S8'), ('S7', 'S7')], default='S18', max_length=25),
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='phone_type',
            field=models.CharField(choices=[('S18', 'S18'), ('A60', 'A60'), ('A04', 'A04'), ('A18', 'A18'), ('C20', 'C20'), ('C19', 'C19'), ('S10', 'S10'), ('10C8G', '10C8G'), ('10C', '10C'), ('8C', '8C'), ('P7P4G', 'P7P4G'), ('P7P3G', 'P7P3G'), ('P7', 'P7'), ('S9', 'S9'), ('9T', '9T'), ('S8', 'S8'), ('S7', 'S7'), ('S10Pro', 'S10Pro')], default='S18', max_length=25),
        ),
    ]
