# Generated by Django 4.2.6 on 2023-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0027_aitel_mifi_storage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitel_mifi_storage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
