# Generated by Django 4.2.6 on 2023-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0029_rename_aitel_mifi_storage_airtel_mifi_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='missing',
            field=models.BooleanField(default=False),
        ),
    ]
