# Generated by Django 4.2.6 on 2023-11-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0030_mainstorage_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtel_mifi_storage',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainstorage',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='airtel_mifi_storage',
            name='device',
            field=models.CharField(choices=[('MIFI', 'MIFI'), ('ROUTER (IDU)', 'ROUTER (IDU)')], default='MIFI', max_length=25),
        ),
    ]
