# Generated by Django 4.2.6 on 2023-12-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0032_mainstorage_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstorage',
            name='read',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
