# Generated by Django 4.2.6 on 2023-12-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0033_remove_mainstorage_read_customerdata_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='read',
        ),
    ]
