# Generated by Django 4.2.6 on 2023-12-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0034_remove_customerdata_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
