# Generated by Django 4.2.6 on 2023-12-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0041_alter_mainstorage_phone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstorage',
            name='battery',
            field=models.CharField(blank=True, choices=[('6000mAh', '6000mAh'), ('5000mAh', '5000mAh'), ('4000mAh', '4000mAh'), ('3000mAh', '3000mAh'), ('2500mAh', '2500mAh'), ('2000mAh', '2000mAh'), ('1500mAh', '1500mAh'), ('1000mAh', '1000mAh')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='camera',
            field=models.CharField(blank=True, choices=[('200MP', '200MP'), ('160MP', '160MP'), ('130MP', '130MP'), ('100MP', '100MP'), ('80MP', '80MP'), ('64MP', '64MP'), ('50MP', '50MP'), ('48MP', '48MP'), ('32MP', '32MP'), ('24MP', '24MP'), ('16MP', '16MP'), ('13MP', '13MP'), ('12MP', '12MP'), ('8MP', '8MP'), ('5MP', '5MP')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='contract_no',
            field=models.CharField(default='##', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='os',
            field=models.CharField(blank=True, choices=[('Android 13', 'Android 13'), ('Android 12', 'Android 12'), ('Android 11', 'Android 11'), ('Android 10', 'Android 10'), ('Android 9', 'Android 9'), ('Android 8', 'Android 8'), ('Android 7', 'Android 7')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('S18', 'S18'), ('A60', 'A60'), ('A04', 'A04'), ('A18', 'A18'), ('C20', 'C20'), ('C19', 'C19'), ('S10Pro', 'S10Pro'), ('S10', 'S10'), ('10C8G', '10C8G'), ('10C', '10C'), ('8C', '8C'), ('P8', 'P8'), ('P7P4G', 'P7P4G'), ('P7P3G', 'P7P3G'), ('P7', 'P7'), ('S9', 'S9'), ('9T', '9T'), ('S8', 'S8'), ('S7', 'S7'), ('it2163', 'it2163'), ('it5607', 'it5607'), ('it5606', 'it5606'), ('it2160', 'it2160'), ('it2171', 'it2171'), ('it2172', 'it2172'), ('13C', '13C'), ('13C Pro', '13C Pro'), ('12C', '12C'), ('12C Pro', '12C Pro'), ('Note 12S', 'Note 12S'), ('Note 12S Pro', 'Note 12S Pro'), ('A2+', 'A2+'), ('A2', 'A2'), ('A1', 'A1'), ('Redmi 10', 'Redmi 10'), ('Redmi 10A', 'Redmi 10A')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='screen_size',
            field=models.CharField(blank=True, choices=[('6.8 inch HD+ display', '6.8 inch HD+ display'), ('6.7 inch HD+ display', '6.7 inch HD+ display'), ('6.6 inch HD+ display', '6.6 inch HD+ display'), ('6.5 inch HD+ display', '6.5 inch HD+ display'), ('6.52 inch HD+ display', '6.52 inch HD+ display'), ('6.5 inch HD+ display', '6.5 inch HD+ display'), ('6.52 inch HD+ display', '6.52 inch HD+ display'), ('6.3 inch HD+ display', '6.3 inch HD+ display'), ('5.5 inch HD+ display', '5.5 inch HD+ display'), ('1.77 inch display', '1.77 inch display')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='spec',
            field=models.CharField(blank=True, choices=[('8+256', '8+256'), ('4+256', '4+256'), ('8+128', '8+128'), ('4+128', '4+128'), ('4+64', '4+64'), ('3+64', '3+64'), ('2+64', '2+64'), ('3+32', '3+32'), ('2+32', '2+32'), ('1+32', '1+32'), ('2+16', '2+16')], max_length=25, null=True),
        ),
    ]
