# Generated by Django 4.2.6 on 2023-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0043_airtel_mifi_storage_collected_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='on_display',
            field=models.BooleanField(default=False),
        ),
    ]
