# Generated by Django 4.2.6 on 2023-12-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0046_alter_mainstorage_battery_alter_mainstorage_camera_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phone_reference',
            new_name='Price_reference',
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='category',
            field=models.CharField(default='Tecno', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mainstorage',
            name='os',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
