# Generated by Django 4.2.6 on 2023-12-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0047_rename_phone_reference_price_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtel_mifi_storage',
            options={'verbose_name_plural': 'Airtel Devices'},
        ),
        migrations.AlterModelOptions(
            name='customerdata',
            options={'verbose_name_plural': 'Customer Details'},
        ),
        migrations.AlterModelOptions(
            name='phonedata',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.AlterModelOptions(
            name='price_reference',
            options={'ordering': ['-price_added_on'], 'verbose_name_plural': 'Price Reference'},
        ),
        migrations.AlterIndexTogether(
            name='phonedata',
            index_together={('customer', 'agent')},
        ),
        migrations.CreateModel(
            name='SpecialOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_orders', models.CharField(max_length=1000)),
                ('initial_balance', models.IntegerField(default=0)),
                ('current_balance', models.IntegerField(default=0)),
                ('final_balance', models.IntegerField(default=0)),
                ('presentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Special Orders',
                'ordering': ['-created_on'],
            },
        ),
    ]
