# Generated by Django 4.2.6 on 2023-12-19 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0048_alter_airtel_mifi_storage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialorders',
            name='presentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
