# Generated by Django 4.2.6 on 2023-12-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0050_alter_specialorders_presentative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialorders',
            options={'verbose_name_plural': 'Special Orders'},
        ),
        migrations.AddField(
            model_name='price_reference',
            name='special_retailer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
