# Generated by Django 4.2.6 on 2023-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0051_alter_specialorders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialorders',
            name='current_orders',
            field=models.IntegerField(default=0),
        ),
    ]
