# Generated by Django 4.2.6 on 2023-12-20 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0052_alter_specialorders_current_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialorders',
            name='last_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialorders',
            name='last_payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
