# Generated by Django 4.2.7 on 2024-01-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0054_airtel_mifi_storage_device_imei_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='device_imei_2',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='price_reference',
            name='current_month',
            field=models.CharField(default='January', max_length=20, null=True),
        ),
    ]
