# Generated by Django 4.2.7 on 2024-01-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0056_alter_phonedata_phone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedata',
            name='phone_type',
            field=models.CharField(default='S18', max_length=25),
        ),
    ]
