# Generated by Django 4.2.7 on 2024-01-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0058_notifications_feedback_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='total_devies_sold',
            new_name='total_devices_sold',
        ),
    ]
