# Generated by Django 4.2.7 on 2024-01-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0061_alter_contact_address_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
