# Generated by Django 4.2.7 on 2024-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0062_useravatar_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(max_length=20),
        ),
    ]
