# Generated by Django 4.2.7 on 2024-01-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0064_feedback_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='faulty',
            field=models.BooleanField(default=False),
        ),
    ]
