# Generated by Django 4.2.7 on 2024-02-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0065_mainstorage_faulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='month',
            field=models.CharField(default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='price_reference',
            name='current_month',
            field=models.CharField(default='February', max_length=20, null=True),
        ),
    ]
