# Generated by Django 4.2.7 on 2024-02-04 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0066_alter_commission_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefarbishedDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('previous_total', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 4, 11, 51, 47, 669665, tzinfo=datetime.timezone.utc))),
                ('date_modified', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 4, 11, 51, 47, 669692, tzinfo=datetime.timezone.utc))),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refarbished Device',
                'verbose_name_plural': 'Refarbished Devices',
                'db_table': 'refarbished_devices',
            },
        ),
        migrations.CreateModel(
            name='FinalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_sold', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 4, 11, 51, 47, 667614, tzinfo=datetime.timezone.utc))),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('previous_total', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 4, 11, 51, 47, 666465, tzinfo=datetime.timezone.utc))),
                ('date_modified', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 4, 11, 51, 47, 666490, tzinfo=datetime.timezone.utc))),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'db_table': 'accessories',
            },
        ),
    ]
