# Generated by Django 4.2.7 on 2024-02-13 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0068_specialorders_current_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialorders',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialorders',
            name='total_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialorders',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 13, 0, 45, 4, 118349, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 13, 0, 45, 4, 118375, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 13, 0, 45, 4, 119463, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 13, 0, 45, 4, 120592, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 13, 0, 45, 4, 120615, tzinfo=datetime.timezone.utc)),
        ),
    ]
