# Generated by Django 4.2.7 on 2024-03-20 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0070_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstorage',
            name='image',
        ),
        migrations.AddField(
            model_name='mainstorage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 20, 0, 6, 49, 103650, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 20, 0, 6, 49, 103673, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commission',
            name='month',
            field=models.CharField(default=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 20, 0, 6, 49, 104799, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='price_reference',
            name='current_month',
            field=models.CharField(default='March', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 20, 0, 6, 49, 105946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 20, 0, 6, 49, 105968, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialorders',
            name='month',
            field=models.CharField(default=3, max_length=20),
        ),
    ]
