# Generated by Django 4.2.7 on 2024-03-23 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0073_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 23, 17, 8, 20, 703584, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 23, 17, 8, 20, 703608, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='airtel_mifi_storage',
            name='cash_recieved_by',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Sahil', 'Sahil'), ('Suhail', 'Suhail'), ('Shehzaad', 'Shehzaad'), ("Sahil's Father", "Sahil's Father")], default='Not Paid', max_length=25),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 23, 17, 8, 20, 704747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 23, 17, 8, 20, 705870, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 23, 17, 8, 20, 705893, tzinfo=datetime.timezone.utc)),
        ),
    ]
