# Generated by Django 4.2.7 on 2024-04-27 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0075_buzzmchinjiprices_chris25prices_chrismzprices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 27, 13, 43, 40, 279097, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 27, 13, 43, 40, 279121, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commission',
            name='month',
            field=models.CharField(default=4, max_length=20),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 27, 13, 43, 40, 280231, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='price_reference',
            name='current_month',
            field=models.CharField(default='April', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 27, 13, 43, 40, 281366, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 27, 13, 43, 40, 281389, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialorders',
            name='month',
            field=models.CharField(default=4, max_length=20),
        ),
    ]
