# Generated by Django 4.2.7 on 2024-05-05 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0076_mainstorage_issue_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='trans_image',
            field=models.ImageField(blank=True, null=True, upload_to='Cash_Transactions'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 5, 16, 12, 19, 717540, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 5, 16, 12, 19, 717568, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commission',
            name='month',
            field=models.CharField(default=5, max_length=20),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 5, 16, 12, 19, 718786, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='price_reference',
            name='current_month',
            field=models.CharField(default='May', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 5, 16, 12, 19, 720001, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 5, 16, 12, 19, 720026, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialorders',
            name='month',
            field=models.CharField(default=5, max_length=20),
        ),
    ]
