# Generated by Django 4.2.7 on 2024-05-16 00:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0077_mainstorage_trans_image_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 16, 0, 51, 32, 162486, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 16, 0, 51, 32, 162511, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 16, 0, 51, 32, 163589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 16, 0, 51, 32, 164707, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 16, 0, 51, 32, 164730, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=9, unique=True)),
                ('date_created', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 16, 0, 51, 32, 186675, tzinfo=datetime.timezone.utc))),
                ('date_updated', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 16, 0, 51, 32, 186706, tzinfo=datetime.timezone.utc))),
                ('active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('rejected', models.BooleanField(default=False)),
                ('issue', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('rejected_proof', models.ImageField(blank=True, null=True, upload_to='rejected_proof/')),
                ('mbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
