# Generated by Django 4.2.7 on 2024-06-01 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0081_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 14, 51, 27, 654452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 1, 14, 51, 27, 628823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 1, 14, 51, 27, 628846, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 14, 51, 27, 654399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 14, 51, 27, 654432, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commission',
            name='month',
            field=models.CharField(default=6, max_length=20),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 1, 14, 51, 27, 629989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='price_reference',
            name='current_month',
            field=models.CharField(default='June', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 1, 14, 51, 27, 631146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 1, 14, 51, 27, 631169, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialorders',
            name='month',
            field=models.CharField(default=6, max_length=20),
        ),
    ]
