# Generated by Django 4.2.7 on 2024-07-01 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0085_accountmanager_important_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountmanager',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountmanager',
            name='payg_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 9, 4, 898909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 9, 4, 898920, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='date_approved',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 9, 4, 909819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 9, 4, 909783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='date_updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 9, 4, 909797, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commission',
            name='month',
            field=models.CharField(default=7, max_length=20),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 9, 4, 899440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='price_reference',
            name='current_month',
            field=models.CharField(default='July', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 9, 4, 899978, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 9, 4, 899988, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialorders',
            name='month',
            field=models.CharField(default=7, max_length=20),
        ),
    ]
