# Generated by Django 4.2.7 on 2024-07-01 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core_1', '0086_accountmanager_customer_name_accountmanager_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainstorage',
            name='mbo_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainstorage',
            name='mbo_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainstorage',
            name='payg_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 33, 5, 258442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 33, 5, 258453, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='date_approved',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 33, 5, 268920, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 33, 5, 268899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='date_updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 33, 5, 268912, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='finalsales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 33, 5, 258965, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 33, 5, 259565, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 1, 1, 33, 5, 259576, tzinfo=datetime.timezone.utc)),
        ),
    ]
