# Generated by Django 4.2.4 on 2023-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptic_core_app', '0006_alter_agentstock_stock_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
