# Generated by Django 4.2.4 on 2023-09-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptic_core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='contract_number',
        ),
        migrations.AddField(
            model_name='phonedata',
            name='contract_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
