# Generated by Django 4.2.4 on 2023-09-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptic_core_app', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstock',
            name='stock_out_date',
            field=models.DateField(null=True),
        ),
    ]
