# Generated by Django 4.2.4 on 2023-09-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptic_core_app', '0004_agentstock_stock_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstock',
            name='stock_out_date',
            field=models.DateField(blank=True),
        ),
    ]
