# Generated by Django 4.2.4 on 2023-10-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptic_core_app', '0005_mainstorage_cryptic_cor_device__f07954_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstorage',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='agentstock',
            index=models.Index(fields=['imei_number', 'phone_type', 'in_stock', 'sold'], name='cryptic_cor_imei_nu_d0e48c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdata',
            index=models.Index(fields=['customer_name', 'national_id', 'customer_contact', 'customer_email'], name='cryptic_cor_custome_a25987_idx'),
        ),
    ]
