# Generated by Django 4.2.4 on 2023-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptic_core_app', '0006_mainstorage_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_sign_up_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
